### ISSUE TITLE
[FEATURE REQ] Dropdown for the maps in main window

### ISSUE THREAD

**Issue by UnicornYames** [The-Nightman/ED-VotingJSON#12]
**Is your feature request related to a problem? Please describe.**
Just clutter on the main window.

**Describe the solution you'd like**
I'd like to see when you select a gamemode on the right, and it populates the main window with maps to select, to be able to close the tree of maps and settings, and only show the title of the gamemode selected for the rotation, in the main screen.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by The-Nightman** [comment]
Added to the list of planned changes, it was not expected that hosts may contain so many maps or gamemodes in the active folders at one time. Expect this either in the next small update to improve styling and bugfixes or the update after.
